repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
      files: \.py$
    - id: end-of-file-fixer
      files: \.py$
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
    - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check # Runs the linter
        args: [ --fix ] # Automatically fixes issues when possible
      - id: ruff-format # Runs the formatter
        files: \.py$